# Generated by Django 3.2.4 on 2021-06-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_Facultad', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('abreviado', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('Facultad_idFacultad', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.facultad')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=55)),
                ('semestre', models.IntegerField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=35)),
                ('fecha_nac', models.DateTimeField()),
                ('Genero', models.CharField(max_length=20)),
                ('Carrera_idCarrera', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.carrera')),
            ],
        ),
    ]
