# Generated by Django 3.2.4 on 2021-06-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
